version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/srv/app
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mariadb"
  mariadb:
    image: mariadb:10.6-focal
    ports:
      - 33061:3306
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MARIADB_DATABASE=votings"
      - "MARIADB_USER=root"
      - "MARIADB_PASSWORD=secret"
      - "MARIADB_ROOT_PASSWORD=secret"
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
volumes:
  mysqldata: